import type { Metadata } from "next";
import "./globals.css";
import { PoppinsFont } from "@/utils/font";
import Drawer from "@/components/Drawer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //
  return (
    <html lang="en" data-theme="mytheme" className={`${PoppinsFont.variable} `}>
      <body>
        <main className="font-poppins">{children}</main>
      </body>
    </html>
  );
}
