import type { Metadata } from "next";
import "./globals.css";
import { PoppinsFont } from "@/utils/font";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="mytheme" className={`${PoppinsFont.variable} `}>
      <body>
        <ToastContainer
          limit={3}
          autoClose={3500}
          draggablePercent={60}
          draggable
        />

        <main className="font-poppins">{children}</main>
      </body>
    </html>
  );
}
