import type { Metadata } from "next";
import "./globals.css";
import { InterFont, PoppinsFont } from "@/utils/font";
import Drawer from "@/components/Drawer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //
  return (
    <html
      lang="en"
      data-theme="mytheme"
      className={`${InterFont.variable} ${PoppinsFont.variable} `}
    >
      <body>
        <main className="font-inter">
          <Drawer>{children}</Drawer>
        </main>
      </body>
    </html>
  );
}
