import re1 from "../../../public/images/r1.png";
import re2 from "../../../public/images/r2.png";
import re3 from "../../../public/images/r3.png";
import re4 from "../../../public/images/r4.png";
import re5 from "../../../public/images/r5.png";
import re6 from "../../../public/images/r6.png";
import work1 from "../../../public/images/work1.png";
import work2 from "../../../public/images/work2.png";
import work3 from "../../../public/images/work3.png";
import work4 from "../../../public/images/work4.png";
import work5 from "../../../public/images/work5.png";
import feat1 from "../../../public/images/feat1.png";
import feat2 from "../../../public/images/feat2.png";
import feat3 from "../../../public/images/feat3.png";

import Image, { StaticImageData } from "next/image";
import { Metadata } from "next";
import clsx from "clsx";
import Link from "next/link";
import { EnvelopeIcon } from "@heroicons/react/24/outline";
import { FaRegCircleCheck } from "react-icons/fa6";
import HeroSection from "@/components/home/HeroSection";
import Title from "@/components/global/Title";
import Cbutton from "@/components/global/Cbutton";
import GetApp from "@/components/global/GetApp";
import FAQs from "@/components/global/FAQS";

export const metadata: Metadata = {
  title: "Home | Trusted Deal Makers",
  // description: "Generated by create next app",
};
interface IHowitWorksItems {
  heading: string;
  description: string;
  img: StaticImageData | string;
}
interface IfeaturesItem {
  heading: string;
  featurelist: string[];
  imgSide: "l" | "r";
  img: StaticImageData | string;
}

const RecognizedByImgs = [re1, re2, re3, re4, re5, re6];

const HowitWorksItems = [
  {
    heading: "Buyer and Customers agree",
    description:
      "The buyer and seller on the Price of the product, mode of delivery, time of delivery and other terms.",
    img: work1,
  },
  {
    heading: "Buyer releases payment to the escrow",
    description:
      "The buyer then releases the agreed price to the escrow for delivery to commence.",
    img: work2,
  },
  {
    heading: "Seller sends out product",
    description: "Seller releases product to buyer and notifies the escrow.",
    img: work3,
  },
  {
    heading: "Buyer receives product",
    description:
      "Buyer receives product and confirms payment release to the seller.",
    img: work4,
  },
  {
    heading: "DealMaker releases payment",
    description: "The escrow releases payment to the seller.",
    img: work5,
  },
];

const featuresItem: IfeaturesItem[] = [
  {
    heading: "Create requests for free!",
    featurelist: [
      "Submit your request",
      "View the list of exciting orders from vendors",
      "Choose what offer suites you",
      "Complete your order with ease",
    ],
    imgSide: "l",
    img: feat1,
  },
  {
    heading: "Pay exactly what you want",
    featurelist: [
      "You only pay what your budget is, nothing more!",
      "With our inline chat you can ask questions about their products or services even before making payments",
      "Both parties have to agree before any transaction is made",
    ],
    imgSide: "r",
    img: feat2,
  },
  {
    heading: "Payments are flexible with Milestones",
    featurelist: [
      "Users can create Milestones and pay as they go on with the services",
      "Users can create different flexible options and agree with clients to work with them",
    ],
    imgSide: "l",
    img: feat3,
  },
];

export default function Home() {
  return (
    <main className="w-full">
      {/* Hero Section */}
      <HeroSection />

      {/* RecognizedBy */}
      {/* <RecognizedBy /> */}

      {/* HowitWorks */}
      <HowitWorks />

      {/* Newsletter */}
      <Newsletter />

      {/* Features */}
      <Features />

      {/* GetApp */}
      <GetApp />

      {/* FAQs */}
      <FAQs />
    </main>
  );
}

export function RecognizedBy() {
  return (
    <section className="bg-[--background_light_blue]">
      <div className="w-full max-w-7xl mx-auto px-4  py-8">
        <Title
          title="Deal Makers is trusted and
          recognized"
        />
        <ul className=" my-4 grid grid-cols-2  sm:grid-cols-3 lg:grid-cols-6 gap-4 ">
          {RecognizedByImgs.map((el, i) => (
            <RecognizedByItem imgsrc={el} key={i} />
          ))}
        </ul>
      </div>
    </section>
  );
}

function RecognizedByItem({ imgsrc }: { imgsrc: StaticImageData | string }) {
  return (
    <li className="md:p-2 grid items-center justify-items-center">
      {/* <div className={"relative w-full h-20"}> */}
      <div className="flex flex-col h-20 w-32 items-center justify-center">
        <Image
          alt="Hero Image"
          // Importing an image will
          // automatically set the width and height
          src={imgsrc}
          sizes="100vw"
          // Make the image display full width
          style={{
            width: "100%",
            height: "auto",
          }}
        />
        {/* </div> */}
      </div>
    </li>
  );
}

function HowitWorks() {
  return (
    <section className="">
      <div className="w-full max-w-7xl mx-auto px-4  py-8">
        <Title title="How TrustedDealMaker  works" />
        <ul className=" my-2 md:my-4 auto-rows-fr justify-items-center grid grid-cols-[repeat(auto-fit,_minmax(250px,_1fr))]  lg:grid-cols-5 gap-4">
          {HowitWorksItems.map((el, i) => (
            <HowitWorksItem item={el} key={i} />
          ))}
        </ul>
        <div className="flex items-center justify-center my-8 gap-6">
          <Link
            href={"#"}
            className="btn btn-primary shadow-md rounded-md justify-end text-white"
          >
            Get Started
          </Link>
          <Link
            href={"#"}
            className="btn btn-primary btn-outline shadow-md rounded-md justify-end"
          >
            Learn More
          </Link>
        </div>
      </div>
    </section>
  );
}

function HowitWorksItem({ item }: { item: IHowitWorksItems }) {
  return (
    <li className="md:shadow pb-2 md:p-4 md:pb-6">
      <div className={"relative w-full  h-28 "}>
        {/* <div className="flex flex-col"> */}
        {/* <div style={{ position: 'relative', height: '400px' }}> */}

        <Image
          alt="Hero Image"
          // Importing an image will
          // automatically set the width and height
          src={item.img}
          // sizes="100vw"
          fill
          // sizes="(min-width: 808px) 50vw, 100vw"
          style={{
            objectFit: "contain", // cover, contain, none
          }}

          // Make the image display full width
          // style={{
          //   width: "100%",
          //   height: "auto",
          // }}
        />
        {/* </div> */}
      </div>
      <div className="flex flex-col">
        <h3 className="text-base font-semibold my-2 text-[--foreground_dark_blue]">
          {" "}
          {item.heading}
        </h3>
        <p className="text-sm">{item.description}</p>
      </div>
    </li>
  );
}

function Newsletter() {
  return (
    <section className="bg-[--background_light_blue]">
      <div className="w-full max-w-7xl mx-auto px-4  py-8">
        <Title
          pill={"Newsletter"}
          subHeading="Subscribe to get 
    information, latest news and other interesting offers 
    about Trusted Deal Maker"
          title="Join Us"
        />
        <label className="form-control w-full max-w-xs my-4 mx-auto">
          <div className="relative">
            <EnvelopeIcon className="absolute inset-y-3 start-0 h-6 px-2 text-primary" />
            <input
              type="email"
              className="rounded-lg input input-bordered w-full pl-10 pr-12 text-sm text-[--fore_dark] shadow-sm"
              placeholder="Enter email ...."
            />

            <div className="absolute inset-y-0 end-0 grid place-content-center px-2 ">
              <Cbutton classes="btn-sm btn-primary rounded-md">
                Subscribe
              </Cbutton>
            </div>
          </div>
        </label>
      </div>
    </section>
  );
}

function Features() {
  return (
    <section className="">
      <div className="w-full max-w-[1400px] mx-auto px-4 py-8 lg:my-12">
        <Title
          title="Your all-in-one Transaction ecosystem"
          subHeading="Bridge the gap between buyers and sellers effortlessly. Your all-in-one marketplace for seamless connections."
        />
        {featuresItem.map((el, i) => (
          <FeatureItem item={el} key={i} />
        ))}
      </div>
    </section>
  );
}

function FeatureItem({ item }: { item: IfeaturesItem }) {
  return (
    <article className="my-12">
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2 lg:gap-16 lg:py-8">
        <div className={clsx(item.imgSide == "r" && "lg:order-last")}>
          <div className="flex flex-col sm:max-w-md md:max-w-lg lg:w-auto mx-auto">
            <Image
              alt="Hero Image"
              // Importing an image will
              // automatically set the width and height
              src={item.img}
              sizes="100vw"
              // Make the image display full width
              style={{
                width: "100%",
                height: "auto",
              }}
            />
          </div>
        </div>

        <div className="">
          <h3 className="text-3xl font-medium md:text-5xl lg:text-6xl md:leading-[1.35] lg:leading-[1.35]">
            {" "}
            {item.heading}
          </h3>
          <ul className="my-4">
            {item.featurelist.map((el, i) => (
              <li key={i} className="inline-flex items-start my-2 ">
                <span className="mr-2 pt-1">
                  <FaRegCircleCheck className="text-primary md:text-xl" />
                </span>
                <span className="text-[--foreground_neutral_base] md:text-lg lg:text-xl lg:leading-relaxed">
                  {el}
                </span>
              </li>
            ))}
          </ul>
          <div>
            <Link
              href={"#"}
              className="btn btn-primary shadow-md rounded-md justify-end text-white md:btn-lg"
            >
              Get Started
            </Link>
          </div>
        </div>
      </div>
    </article>
  );
}
